[internal-users]
; Pattern for the departments (100 to 106)
exten => _10X,1,Dial(PJSIP/${EXTEN},30,t)
 same => n,Hangup()

; Pattern for lamdas peoples (yes we the polytech are lambdas here)
exten => _7XXXXXXXX,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

; Pattern for test only
exten => _2XXX,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()
exten => _3XXX,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

; SVI my friend
; --- Entrance to the SVI ---
exten => 500,1,Answer()
 same => n,Set(TIMEOUT(digit)=2)     ; Give people 2 seconds between digits
 same => n,Set(TIMEOUT(response)=10)  ; Give them 10 seconds to make a choice
 same => n(start),Background(digits/1) ; Play the recorded menu
 same => n,WaitExten()               ; Wait for them to press a key

; --- SVI Choices ---
exten => 1,1,Dial(PJSIP/100,20)      ; Press 1 -> Direction
exten => 2,1,Dial(PJSIP/101,20)      ; Press 2 -> Infirmary
exten => 3,1,Dial(PJSIP/102,20)      ; Press 3 -> CRI
exten => 4,1,Dial(PJSIP/103,20)      ; Press 4 -> GIT
exten => 5,1,Dial(PJSIP/104,20)      ; Press 5 -> GC
exten => 6,1,Dial(PJSIP/105,20)      ; Press 6 -> GM
exten => 7,1,Dial(PJSIP/106,20)      ; Press 7 -> TC

; --- Error Handling ---
exten => i,1,Playback(invalid)       ; "i" is for Invalid choice
 same => n,Goto(500,start)

exten => t,1,Playback(vm-goodbye)    ; "t" is for Timeout (they took too long)
 same => n,Hangup()

;--- SMS Handling ---
exten => _XXXX,1,NoOp(SMS receiving for ${EXTEN})
 same => n,Set(TARGET_ADDR=pjsip:${EXTEN})
 same => n,MessageSend(${TARGET_ADDR},${MESSAGE(from)})
 same => n,Hangup()





