[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; --- Master Template ---
[endpoint-template](!)
type=endpoint
direct_media=yes
allow_transfer=yes
dtmf_mode=rfc4733
disallow=all
allow=ulaw,alaw
max_contacts=5                  ; allow user to connect up to 5 diff IPs (up to 5 diff devices then)
remove_existing=yes             ; if it exeed 5, the oldest one is replace

; --- User A: 770000000 ---
[770000000](endpoint-template)
context=internal-users
auth=auth770000000
aors=770000000

[auth770000000]
type=auth
auth_type=userpass
username=770000000
password=pass

[770000000]
type=aor
max_contacts=1

; --- User B: 770000001 ---
[770000001](endpoint-template)
context=internal-users
auth=auth770000001
aors=770000001

[auth770000001]
type=auth
auth_type=userpass
username=770000001
password=pass

[770000001]
type=aor
max_contacts=1

; ================ Departments ===================

; --- 100: Direction ---
[100](endpoint-template)
context=internal-users
callerid=Direction EPT
auth=auth100
aors=100

[auth100]
type=auth
auth_type=userpass
username=100
password=pass

[100]
type=aor
max_contacts=1

; --- 101: Infirmary ---
[101](endpoint-template)
context=internal-users
callerid=Infirmarie EPT
auth=auth101
aors=101

[auth101]
type=auth
auth_type=userpass
username=101
password=pass

[101]
type=aor
max_contacts=1

; --- 102: CRI ---
[102](endpoint-template)
context=internal-users
callerid=CRI EPT
auth=auth102
aors=102

[auth102]
type=auth
auth_type=userpass
username=102
password=pass

[102]
type=aor
max_contacts=1

; --- 103: GIT ---
[103](endpoint-template)
context=internal-users
callerid=Departement GIT
auth=auth103
aors=103

[auth103]
type=auth
auth_type=userpass
username=103
password=pass

[103]
type=aor
max_contacts=1

; --- 104: GC ---
[104](endpoint-template)
context=internal-users
callerid=Departement GC
auth=auth104
aors=104

[auth104]
type=auth
auth_type=userpass
username=104
password=pass

[104]
type=aor
max_contacts=1

; --- 105: GM ---
[105](endpoint-template)
context=internal-users
callerid=Departement GM
auth=auth105
aors=105

[auth105]
type=auth
auth_type=userpass
username=105
password=pass

[105]
type=aor
max_contacts=1

; --- 106: TC ---
[106](endpoint-template)
context=internal-users
callerid=Departement TC
auth=auth106
aors=106

[auth106]
type=auth
auth_type=userpass
username=106
password=pass

[106]
type=aor
max_contacts=1